// <auto-generated />
using System;
using FYP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260104000413_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FYP.Models.ActionType", b =>
                {
                    b.Property<int>("ActionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionTypeID"));

                    b.Property<string>("ActionTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ActionTypeID");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("FYP.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique()
                        .HasFilter("[CustomerID] IS NOT NULL");

                    b.HasIndex("EmployeeID")
                        .IsUnique()
                        .HasFilter("[EmployeeID] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FYP.Models.AuditLog", b =>
                {
                    b.Property<int>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FYP.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("PictureBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FYP.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FYP.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GuestID");

                    b.HasIndex("Email");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("FYP.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("GuestID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatusID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<bool>("ReservationType")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedFor")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReservationDate");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("GuestID");

                    b.HasIndex("ReservationStatusID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_CustomerOrGuest", "((CustomerID IS NOT NULL AND GuestID IS NULL) OR (GuestID IS NOT NULL AND CustomerID IS NULL))");
                        });
                });

            modelBuilder.Entity("FYP.Models.ReservationLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("ActionTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogID");

                    b.HasIndex("ActionTypeID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationLogs");
                });

            modelBuilder.Entity("FYP.Models.ReservationStatus", b =>
                {
                    b.Property<int>("ReservationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationStatusID");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            ReservationStatusID = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Description = "Awaiting confirmation",
                            StatusName = "Pending",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            ReservationStatusID = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Description = "Confirmed by staff/system",
                            StatusName = "Confirmed",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            ReservationStatusID = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Description = "Customer seated",
                            StatusName = "Seated",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            ReservationStatusID = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Description = "Reservation completed",
                            StatusName = "Completed",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            ReservationStatusID = 5,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Description = "Cancelled by customer/staff",
                            StatusName = "Cancelled",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("FYP.Models.ReservationTables", b =>
                {
                    b.Property<int>("ReservationTablesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationTablesID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationTablesID");

                    b.HasIndex("ReservationID");

                    b.HasIndex("TableID");

                    b.ToTable("ReservationTables");
                });

            modelBuilder.Entity("FYP.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SettingsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RestaurantID");

                    b.HasIndex("SettingsID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantID = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            SettingsID = 1,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("FYP.Models.Settings", b =>
                {
                    b.Property<int>("SettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SettingsID");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            SettingsID = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Key = "Name",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system",
                            Value = "Fine O Dine"
                        },
                        new
                        {
                            SettingsID = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Key = "Opening Hours",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system",
                            Value = "10:00 - 22:00"
                        },
                        new
                        {
                            SettingsID = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Key = "Phone",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system",
                            Value = "+1 555 123 4567"
                        },
                        new
                        {
                            SettingsID = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            Key = "Staff Number",
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system",
                            Value = "0"
                        });
                });

            modelBuilder.Entity("FYP.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsJoinable")
                        .HasColumnType("bit");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TableID");

                    b.HasIndex("RestaurantID", "TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 1,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 2,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 2,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 3,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 3,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 4,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 4,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 5,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 5,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 6,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 6,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 7,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 7,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 8,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 8,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 9,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 9,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 10,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = true,
                            RestaurantID = 1,
                            TableNumber = 10,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 11,
                            Capacity = 8,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = false,
                            RestaurantID = 1,
                            TableNumber = 11,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            TableID = 12,
                            Capacity = 8,
                            CreatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            IsAvailable = true,
                            IsJoinable = false,
                            RestaurantID = 1,
                            TableNumber = 12,
                            UpdatedAt = new DateTime(2025, 10, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("FYP.Models.TablesJoin", b =>
                {
                    b.Property<int>("TablesJoinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TablesJoinID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JoinedTableID")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryTableID")
                        .HasColumnType("int");

                    b.Property<int?>("TableID")
                        .HasColumnType("int");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TablesJoinID");

                    b.HasIndex("JoinedTableID");

                    b.HasIndex("PrimaryTableID");

                    b.HasIndex("TableID");

                    b.ToTable("TablesJoins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FYP.Models.ApplicationUser", b =>
                {
                    b.HasOne("FYP.Models.Customer", "Customer")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("FYP.Models.ApplicationUser", "CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP.Models.Employee", "Employee")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("FYP.Models.ApplicationUser", "EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FYP.Models.Employee", b =>
                {
                    b.HasOne("FYP.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FYP.Models.Reservation", b =>
                {
                    b.HasOne("FYP.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP.Models.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP.Models.ReservationStatus", "ReservationStatus")
                        .WithMany()
                        .HasForeignKey("ReservationStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Guest");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FYP.Models.ReservationLog", b =>
                {
                    b.HasOne("FYP.Models.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Reservation", "Reservation")
                        .WithMany("ReservationLogs")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FYP.Models.ReservationTables", b =>
                {
                    b.HasOne("FYP.Models.Reservation", "Reservation")
                        .WithMany("ReservationTables")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.Table", "Table")
                        .WithMany("ReservationTables")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("FYP.Models.Restaurant", b =>
                {
                    b.HasOne("FYP.Models.Settings", "Settings")
                        .WithMany("Restaurants")
                        .HasForeignKey("SettingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("FYP.Models.Table", b =>
                {
                    b.HasOne("FYP.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FYP.Models.TablesJoin", b =>
                {
                    b.HasOne("FYP.Models.Table", "JoinedTable")
                        .WithMany()
                        .HasForeignKey("JoinedTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Table", "PrimaryTable")
                        .WithMany()
                        .HasForeignKey("PrimaryTableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP.Models.Table", null)
                        .WithMany("JoinedTables")
                        .HasForeignKey("TableID");

                    b.Navigation("JoinedTable");

                    b.Navigation("PrimaryTable");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FYP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FYP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FYP.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FYP.Models.Customer", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FYP.Models.Employee", b =>
                {
                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FYP.Models.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FYP.Models.Reservation", b =>
                {
                    b.Navigation("ReservationLogs");

                    b.Navigation("ReservationTables");
                });

            modelBuilder.Entity("FYP.Models.Settings", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FYP.Models.Table", b =>
                {
                    b.Navigation("JoinedTables");

                    b.Navigation("ReservationTables");
                });
#pragma warning restore 612, 618
        }
    }
}
